#!/bin/bash

# checkelasticsearch 
# Copyright 2013 Sujith Jose <sjose@win2ix.ca> http://www.win2ix.ca
# version = '0.1';

#Begin GPL
#    This file is part of checkelasticsearch.
#
#    checkelasticsearch is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    checkelasticsearch is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with checkelasticsearch.  If not, see <http://www.gnu.org/licenses/>.
#End GPL

#Checking with the status of elasticsearch

`/etc/init.d/elasticsearch status > /tmp/elasticsearchstatus `
STATE=`cat /tmp/elasticsearchstatus | awk '{print $5$6}'`

#Setting the status based on the state
case "$STATE" in
        runningwith)
                        status=0
                        statustxt=OK
                        ;;
        notrunning)
                        status=2
                        statustxt=CRITICAL
                        ;;
        *)
                        status=2
                        statustxt=CRITICAL
                        ;;
esac

echo "$status elasticsearch_status - $statustxt Elasticsearch status is $statustxt "
